domain: AvailableForTheWorld.github.io
url: https://AvailableForTheWorld.github.io
baseurl: '' # Leave empty for user sites
title: my blog
email: 435829792@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  for blog posts
github_username: jekyll
theme: minima
sass:
  sass_dir: _sass
permalink: /posts/:title/ # Add this line for cleaner URLs
