source "https://mirrors.tuna.tsinghua.edu.cn/rubygems/"

gem "jekyll", "~> 4.3.2"
gem "minima", "~> 2.5"

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-seo-tag", "~> 2.8"
end

